### ISSUE TITLE
[Taskbar height and icon size] Requires explorer restart every time

### ISSUE THREAD

**Issue by moccor** [ramensoftware/windhawk-mods#1046]
Is there a way or setting to not have to restart explorer.exe every single time? Like a checkbox that says "do this automatically upon WindHawk startup" or is it supposed to just "save" but it isn't for me? I really enjoy this mod, but having to restart explorer each time can be annoying.

As for the log, I enabled it but I wasn't seeing anything in it so I am not sure about the log part.

**Comment by m417z** [comment]
I don't understand the problem. When does the problem happen? What exactly happens?

**Comment by moccor** [comment]
Is it intended for the explorer.exe to be required to restart every time? If so I can just close this "issue", I am just under the impression there might be something wrong with it/my install. I load the software and it changes the icon size, the taskbar height, but it doesn't automatically change the taskbar width without having to restart explorer.exe. So it loads with tiny icons the way I want, but they are spaced like normal giant icons, so it defeats the purpose until the explorer.exe is restarted.

If that is how it is designed then that is fair, its no problem. But it would be cool if there was like a checkbox/toggle for "auto restart explorer.exe" if that is the only way for it to work as intended. Thanks for the help

**Comment by m417z** [comment]
The way it's implemented right now requires a restart. I thought users mostly have Windhawk running at system startup, and not starting and stopping it in the middle, so it's not an issue. I'll see what I can do to improve it.

**Comment by moccor** [comment]
If that is the intended way to have it work correctly, I will do that, I have np with that. I was going to do that initially, but I thought if it runs at startup and then makes the icons tiny with the giant icon spacing, it would defeat the purpose of running at start. I am gonna give it a try with running it at startup right now

**Comment by m417z** [comment]
The best way to use Windhawk is to install the standard (not portable) version, then you also don't need to add it to the startup folder, it will start on boot automatically. Are you using the portable version?

**Comment by moccor** [comment]
Yes I was using the portable version. I never used it before so I wanted to try it in portable mode first. That makes a lot of sense now. I will install it and give it a try with a reboot.

**Comment by dubbat** [comment]
Also using the portable version and did add it to startup. Glad and saddened that it is not a bug but intended. Would be nice if the portable version would check if it needs to restart explorer (non-standard width) and auto restart explorer.exe. I really don't see the reason why not to when it automatically resizes everything else but can't do the width. A tickbox to to enable auto-restart (if needed) would be nice. Otherwise, I have to change the size, hit apply, say no to restart, change the size back, hit yes to restart on every bootup or every relaunch of windhawk. Alternatively, obviously, I could install the full version instead of portable, but this should be explained somewhere if this feature is not to be implemented as it is a huge annoyance.

Maybe this is an issue of Windhawk itself and not the plugin though? I really don't like having to install anything. I want it to work exactly as I had it on a previous install minus the startups, which is easily fixed, and not having to scour for appdata folders to backup settings etc.

**Comment by m417z** [comment]
> Glad and saddened that it is not a bug but intended

It's not intended in the sense that I could easily implement one of the two options, and I decided to go with requiring to restart explorer. Applying it without restarting explorer requires additional effort due to the way the option is implemented, because the width value is read on startup, and just changing it doesn't affect elements that were already created.

> I really don't see the reason why not to when it automatically resizes everything else but can't do the width

The other options have a different implementation.

In any case, restarting explorer is no longer required in version 1.2.15 of the mod.
