### ISSUE TITLE
[Taskbar height and icon size] Taskbar overflow to bottom issue on Windows 11 24H2 Build 26100.2033

### ISSUE THREAD

**Issue by vathanac** [ramensoftware/windhawk-mods#1072]
![image](https://github.com/user-attachments/assets/e333df38-1dea-4ae2-8f96-ba624aabdb91)

**Comment by m417z** [comment]
Hopefully fixed with the improvements in version 1.2.13 as discussed in https://github.com/ramensoftware/windhawk-mods/issues/529#issuecomment-2417127448. If not, please let me know and I'll reopen the issue.

**Comment by Dani-8** [comment]
guys is it even trust worthy i'm installing and its showing a warning so just asking

**Comment by m417z** [comment]
@Dani-8 In the case of the Taskbar height and icon size mod, you can trust it since you're already trusting Windhawk (you installed it), and the mod author is the same person (me). But it's a good exercise to understand why you can trust it.

In case of other mods, as the note says, make sure you trust the mod author, or carefully inspect the source code before installing. Eventually, it's your responsibility, just like when installing programs or compiling and running code from GitHub (which is not necessarily safe).

I do go over the code before accepting mod submissions, but for non-trivial mods, it's not really possible to assure with full certainty that the mod contains no malicious code.
