### ISSUE TITLE
(Better File Sizes in File Explorer) @m417z Runtime Error - Not Enough space for thread Data

### ISSUE THREAD

**Issue by Deathbot64** [ramensoftware/windhawk-mods#1178]
Every time I open explorer after adding this mod I get this error:

![Screenshot 2024-10-30 122153](https://github.com/user-attachments/assets/b6afbd4e-758b-4ca0-a66c-26a26747e92f)

**Comment by Deathbot64** [comment]
@m417z

**Comment by Alienmoon** [comment]
> Every time I open explorer after adding this mod I get this error:
> 
> ![Screenshot 2024-10-30 122153](https://private-user-images.githubusercontent.com/74361687/381641606-b6afbd4e-758b-4ca0-a66c-26a26747e92f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzMDgyODcsIm5iZiI6MTczMDMwNzk4NywicGF0aCI6Ii83NDM2MTY4Ny8zODE2NDE2MDYtYjZhZmJkNGUtNzU4Yi00Y2EwLWE2NmMtMjZhMjY3NDdlOTJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDE3MDYyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4MDI0ZmFhNGU1YjI3MTRhZTliZGIyYmUzNGFiNTAxYTI4MWJlYzE2NWRjY2UxYTg5YjFkODk0Yzc0M2UwMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.stv2nnZQoD1-vvdPe0qDAjbk7PA1sdb6kUAOmJhC2e4)

Working fine here
![db9dab11bea780d56f390befce3a4cc0](https://github.com/user-attachments/assets/cf500aed-ebe9-4a37-bf63-a6bcfa0211de)

And these are the Runtimes C++ i have installed, most installed by games.
![23a4af851b6384b3b84e03060c189c91](https://github.com/user-attachments/assets/7a772e9d-7365-40ad-b4e4-e6980779e3d1)

**Comment by m417z** [comment]
It's a known issue with any mod that injects into explorer and uses the C++ runtime library. The problem is caused by a combination of Windhawk and msvcrt (Microsoft C runtime library), and may happen when a new explorer.exe process starts, sends a message to the main explorer.exe process to open a new window, and exits right away. That doesn't happen in most cases (opening a new folder, Win+E, etc.), but may happen if you run explorer.exe directly via a shortcut, Win+R, etc.

A workaround will be added to the next Windhawk version. Meanwhile, you can install this mod as a temporary workaround:
https://gist.github.com/m417z/f0cdf071868a6f31210e84dd0d444055

To install it, click the bottom right button to create a new mod, replace the code, click "Compile Mod", then "Exit Editing Mode".

**Comment by m417z** [comment]
I just released version 1.5.2 which includes a workaround to this problem. Please try it and let me know whether it works.

**Comment by Deathbot64** [comment]
Seems to be good so far. If I see any issues I will follow up

**Comment by Deathbot64** [comment]
I had another runtime error pop up. I'll keep an eye out for more but I had
to leave for the day

**Comment by Susexe** [comment]
@m417z, this still happens to me. It usually occurs when I open File Explorer by left-clicking the toolbar icon, and only rarely (if at all) when using `Win + E`.

**Comment by m417z** [comment]
@Susexe the issue should be fixed in Windhawk 1.6. From the changelog:

> Fixed an error caused by Windhawk in some cases: "Not enough space for thread data." To apply the fix, install or update at least one mod after the Windhawk update, then restart Windhawk.

Did you follow the steps to have the fix applied?

Also, does the issue happen only when the mod is enabled? It might be unrelated to Windhawk.

**Comment by Susexe** [comment]
@m417z, the problem is unrelated to Windhawk, sorry. I'm not sure what causes it, but when performing the same steps without Windhawk running, a similar but completely blank dialog appears:

<img width="181" height="169" alt="Image" src="https://github.com/user-attachments/assets/77f18bd0-8139-4a9e-8da3-5037a64ae1e2" />

**Comment by m417z** [comment]
Some users reported that Nilesoft Shell caused it for them. Are you using it? If not, you might want to look for other customization tools.

**Comment by Susexe** [comment]
Thanks! It was indeed Nilesoft Shell. I guess I'll ignore it since it happens rarely, because I just love that tool.

**Edit:** It was fixed by repinning File Explorer to the taskbar.
