### ISSUE TITLE
[Better file sizes in Explorer details] No folder sizes on Windows 10 1607

### ISSUE THREAD

**Issue by legacy1477** [ramensoftware/windhawk-mods#1245]
The mod does not show folder sizes on Windows 10 1607 14393.7259.

I have tried it on a VM with the same Windows version without an AV active, with allowing Windhawk to use system processes from advanced options.
I have tried both manual and Everything methods, none show anything.
I installed the normal version of everything without service mode.
Then re-installed with service mode.
I restarted the VM multiple times with no luck.

Also, the mod seems to inject quite frequently into almost every process. Stuff like DWM, cmd and etc. Stuff that doesn't have any UI or will never utilize this in any way. Winpython seemed to have issues injecting and the injection window remained opened till I restarted Windhawk.
I suggest only injecting into explorer.exe and allowing people to manually specify which applications they'd like this mod to inject into.

**Comment by m417z** [comment]
I didn't test the mod on Windows 10 versions other than the latest build.

Please attach debug logs by following the instructions on the Troubleshooting page:
https://github.com/ramensoftware/windhawk/wiki/Troubleshooting#some-or-all-windhawk-mods-dont-work

> * Disable the mod.
> * Go to the mod's Advanced tab.
> * Set **Debug logging** to **Detailed debug logs**.
> * Click on **Show log output**.
> * Enable the mod.
> * Verify that the mod doesn't work, copy the log and save it to a file.
> * Set **Debug logging** back to **None**.

> Winpython seemed to have issues injecting and the injection window remained opened till I restarted Windhawk.

That sounds like something that shouldn't happen. What does the injection window show? Does it happen every time? Does it only happen on this Windows 10 build?

> I suggest only injecting into explorer.exe and allowing people to manually specify which applications they'd like this mod to inject into.

There are several Windhawk mods which customize various aspects of the file explorer elements, and most/all of them target all processes. I'll consider changing it for "Better file sizes in Explorer details" since it's a popular mod if it causes a significant amount of problems. For now, I don't think there are enough reasons for that.

Generally, the mod hooks several functions, and if a process never shows the explorer UI then these functions will never be called, and so the mod should have no effect.  If that's not the case, perhaps it's a bug that's worth investigating.

**Comment by m417z** [comment]
I downloaded and extracted WinPython. What should I do next to reproduce the issue?

**Comment by m417z** [comment]
> [debug.txt](https://github.com/user-attachments/files/17782671/debug.txt)

One of the symbols is different in this older Win10 version. Please try this mod version:
https://github.com/m417z/my-windhawk-mods/blob/055b82436ccf22eba85c422c0f785e26ba1d8784/mods/explorer-details-better-file-sizes.wh.cpp

To try it, disable the existing mod, then click the bottom right button to create a new mod, replace the code with the test mod code, click "Compile Mod", then "Exit Editing Mode".

> When it injected into every process even hidden console apps it spiked the CPU like crazy.

When enabled for the first time, it needs to do some symbol initialization, so that's expected, but it shouldn't spike the CPU after the initialization is completed at the first time. Can you see if it's an issue after the first initialization is completed?

> I can attach the script if you want, not sure if you'll be able to get it stuck like it was for me.

Can you still reproduce it? Does it stuck for a long time (say, 30 seconds or a minute), or for what seems to be forever? What's the status that's shown?

**Comment by tasskkil** [comment]
все еще не работает, странно, вроде бы популярный мод, но до сих пор есть проблемы...
