### ISSUE TITLE
[Customize Windows notifications placement] Option to have the notifications spawn in the monitor where the cursor is.

### ISSUE THREAD

**Issue by JotaRata** [ramensoftware/windhawk-mods#1247]
Mod creator: @m417z

Hello.

I have this neat idea of showing an option to have the notifications positioned in the monitor where the cursor currently is.
I think this would be nice for people who have to work in a dual-desktop environment and uses messaging services like WhatsApp and Discord often, since you can more easily read notifications when they appear in the monitor you're currently looking at, instead of having to look to the other monitor which (depending of the configuration) can be harder to read.

**Comment by MuscularPuky** [comment]
although it's bug, I rarely meet 2nd monitor nofity when I close the rid. was cool bug

**Comment by MuscularPuky** [comment]
although it's bug, I meet sometimes 2nd monitor nofity when I've closed the rid. was cool bug

**Comment by m417z** [comment]
Nice idea, added in version 1.0.2.

**Comment by JotaRata** [comment]
Works like a charm. Thank you!

**Comment by KKire** [comment]
Interesting option. I have an opposite idea to this. Make the notifications appear on the other monitor where the cursor is not on. Reason: A huge margin around the notification is unclickable when it's displayed and can get in a way when you want to click on something when notification appears.

Not sure **I** will actually use this feature so that's why I'm not even creating a new issue, but writing my idea somewhere 😅
