### ISSUE TITLE
'Middle click to close on taskbar' incompatible with StartAllBack

### ISSUE THREAD

**Issue by derickso** [ramensoftware/windhawk-mods#1281]
[log.txt](https://github.com/user-attachments/files/17909996/log.txt)

**Comment by m417z** [comment]
StartAllBack 3.8 uses its own taskbar, and most Windhawk mods don't work with it.

If you're using StartAllBack older than version 3.8, it uses the old Win10 taskbar. For the Middle click to close on the taskbar mod, there's an option that can be enabled to make it work, "Customize the old taskbar on Windows 11".

**Comment by The111** [comment]
> StartAllBack already supports middle click to close. Just uncheck combine taskbar buttons. Not really intuitive, I know.

Thank you so much for this, I just spent many hours frustrated by 24H2, and seeing this comment earlier would have saved me. However, it's even LESS intuitive now. My dropdown already showed this, so I was confused why it wasn't working:

![Image](https://github.com/user-attachments/assets/a673d768-c4f7-4df0-91f5-0d0cc0be2ae2)

It turns out there are THREE "never" settings, and you have to choose "Never group" now to get that behavior.
