### ISSUE TITLE
Mod Request: Always Show Tray Icons

### ISSUE THREAD

**Issue by KKire** [ramensoftware/windhawk-mods#146]
This feature is missing in 11 but present in 10.
It can be enabled temporary via control panel if you open notification area settings somehow, but it is ignored on explorer restart
![image](https://user-images.githubusercontent.com/23094767/226717022-aa062ec9-b19c-4f0c-8d66-1059e9937b4e.png)

**Comment by XP1** [comment]
Need to set `IsPromoted` to `1` for each key in "`HKEY_CURRENT_USER\Control Panel\NotifyIconSettings`".

I run this PowerShell script "`Show tray icons.ps1`" periodically:

```
Get-ChildItem "HKCU:\Control Panel\NotifyIconSettings" | ForEach-Object {
    Set-ItemProperty -Path $_.PSPath -Name "IsPromoted" -Type "DWORD" -Value 1
}
```

**Comment by m417z** [comment]
Done, check out [Always show all taskbar tray icons](https://windhawk.net/mods/taskbar-notification-icons-show-all).

**Comment by KKire** [comment]
Great! Thanks!
Does it promote the icons, similarly like the powershell script above or it just force shows them like in Windows 10?

**Comment by m417z** [comment]
The mod has two modes that can be selected in the mod settings:
1. All icons are shown. That's the default, and like in the gif below, all icons become shown when the mod is enabled.
2. New icons are shown, existing icons are unaffected. If this mode is selected, the mod only affects icons of new apps, which become visible by default instead of being hidden.

![e634cb06e6](https://github.com/user-attachments/assets/034f19f7-8ad3-4be1-9f6a-f117d5e7b5bb)
