### ISSUE TITLE
Mod request: Move Windows 11 taskbar to the top

### ISSUE THREAD

**Issue by ItsProfessional** [ramensoftware/windhawk-mods#166]
I do not want to use the Windows 10 taskbar in Win11 using registry hacks, and I wish to move the Windows 11 taskbar to the top of my screen.

Start11 can do this, so one could try figuring out its implementation

Edit: Also, if the taskbar has been moved to the top, the flyouts should also pop-out from the top. StartAllBack has proved that changing the location from where these flyouts popup is possible

So a windhawk mod that moves the taskbar to the top like Start11 and causes flyouts to popout from the top like StartAllBack would be nice (you can't have both of these programs running at once, that's why I'm making this issue)

**Comment by Cubody** [comment]
Is there any news regarding this feature?

**Comment by m417z** [comment]
Done! Check out the [Taskbar on top for Windows 11](https://windhawk.net/mods/taskbar-on-top) mod.

**Comment by Cubody** [comment]
Nice! Thanks a lot. But I found a couple of problems. If you right-click on one of the tray icons in the group (sounds, wi-fi, battery), the window opens, but does not respond, you cannot select anything. The notification Center opens from the bottom, not from the top. Otherwise, it seems to be perfect =)

I also wanted to know if something like smart transparency of StartAllBack is possible? When the desktop is transparent, when the application is open to full screen, it is opaque

**Comment by m417z** [comment]
> If you right-click on one of the tray icons in the group (sounds, wi-fi, battery), the window opens, but does not respond, you cannot select anything

Please create an issue. Meanwhile you can use the keyboard.

> The notification Center opens from the bottom, not from the top

It's a known limitation, I didn't look at it yet. You can create an issue for that too, thanks.

> I also wanted to know if something like smart transparency of StartAllBack is possible? When the desktop is transparent, when the application is open to full screen, it is opaque

There's this fairly new mod which does something like that:
https://windhawk.net/mods/taskbar-background-helper

**Comment by Cubody** [comment]
https://github.com/ramensoftware/windhawk/issues/293 (tray icons bug)
https://github.com/ramensoftware/windhawk/issues/294 (notification center bug)
