### ISSUE TITLE
[Never combine taskbar & showing label] Implement with Windows 11 build 23466 and keep the option of the mod?

### ISSUE THREAD

**Issue by codezi** [ramensoftware/windhawk-mods#227]
Hello,
Great news today: "On [Windows 11 build 23466](https://pureinfotech.com/windows-11-build-23466-dev/), you can enable an early preview of the new option to show labels in the Taskbar, and in this guide, you will learn how. Microsoft is working on bringing back the "Combine taskbar buttons and hide labels" settings to allow users to show labels in two ways, including "never combine" or "combine only when the Taskbar is full."
See more: https://pureinfotech.com/show-taskbar-labels-never-combine-windows-11/
The question is: Can the mod update to use this native option of Windows 11 but still keep the option of the mod: "Taskbar item width"? Because the width of the taskbar item on native Windows 11 looks so bad.
<img width="428" alt="Screenshot 2023-05-25 at 22 17 47" src="https://github.com/ramensoftware/windhawk-mods/assets/19167750/a0e2bc89-522f-4897-8ea8-9fa89cd56ebb">
Thank you.

**Comment by Tellinq** [comment]
I’m on the that build right now and prefer the dynamic width as I don’t want empty space on my desktop. I’m curious why you don’t prefer that over static width. Does it hinder your usability when clicking apps on the taskbar?

Are you also getting the behavior where if you attempt to enable WH’s taskbar labels it just results in empty blank space and the buttons just shift?

**Comment by codezi** [comment]
Hello,
Just because my workflow is used to it like that, so that is why I want the dynamic width option.
Thank you.

**Comment by khazidhea** [comment]
I'm on the 23471 build and the "Taskbar Labels" mod is broken.
My taskbar looks like this with mod enabled:

![image](https://github.com/ramensoftware/windhawk-mods/assets/1207334/9374c149-3e20-4ec2-97fa-1e83313e2743)

I prefer the mod over native implementation since it shows stuff like page title and not just "Google Chrome".
For reference this is how it looks like with mod disabled and native implementation enabled:

![image](https://github.com/ramensoftware/windhawk-mods/assets/1207334/315f1598-57b8-4609-bfd9-e78d777c2866)


Is there any way to fix this?

**Comment by khazidhea** [comment]
@m417z Sorry for bothering you, but is this possible to fix, are you planning to?

Do you need any debug info?

**Comment by m417z** [comment]
Done in version 1.2 of the mod, it now uses the native labels implementation when possible, while still allowing to customize options such as the button width.
