### ISSUE TITLE
"Close with middle click" does not work with old taskbar

### ISSUE THREAD

**Issue by ttodua** [ramensoftware/windhawk-mods#23]
With ExplorerPatcher, we get the old taskbar (where 7+tweaker's setting "close item by mousewheel click" worked), however, windhawk's mod "Middle click to close on the taskbar" does not work. Would be nice if WindHawk supported that too.

**Comment by m417z** [comment]
My focus with the "Middle click to close on the taskbar" mod was the Windows 11 taskbar, since for the Windows 10 taskbar there's 7+ Taskbar Tweaker, for which I assumed that most users will just use (or keep using) the tweaker.

I did some simple detection of Windows 10 vs. Windows 11 in the mod, since most of the code works for both, but detecting the Windows 10 taskbar on Windows 11 is extra effort which I'm not sure is worth it.

I'll see if I get this request from other users. For now, you have the following options:

* Use 7+ Taskbar Tweaker.
* Edit the mod's code - choose "Fork" instead of "Install", and replace this line - `HMODULE module = LoadLibrary(L"taskbar.dll");` - with this - `HMODULE module = nullptr;`, then click on "Compile Mod". I didn't test it with Explorer Patcher but I believe that it should work.

**Comment by ttodua** [comment]
thanks for the answer.
The reason is that, WindHawk seems the correct route to go with and in future, so I am trying to leave using 7+tweaker, as WH offers drastically new and correct way of doing things and it is the future. So, I dont want to have running 2 apps simultaneously in windows, to  customize taskbar, so I wished all of things were done/manageable from single place (and that is WH). 7+ tweaker had been excellent, but I duobt WH's time has come now, as it's vastly better/innovated route. 
Thanks for excellent apps.

**Comment by ttodua** [comment]
@m417z is there any chance, that you might find 2 minutes to add support for it? I used your above suggestion in fork and it works, but closes all windows of that program, not only the window which is middle-clicked on.

**Comment by m417z** [comment]
It's not a 2 minute task. I didn't forget about it, it's just that I'm busy with other things. For now, you can just use 7+ Taskbar Tweaker.

**Comment by m417z** [comment]
Fixed in version 1.0.2 of the mod.
