### ISSUE TITLE
move systray to secondary monitor

### ISSUE THREAD

**Issue by d0vere** [ramensoftware/windhawk-mods#334]
is it possible to move systray to a secondary monitor? i have 4 monitors setup and i'd like to move it to my right monitor

**Comment by m417z** [comment]
Sounds like changing the main display is what you're looking for:
https://www.elevenforum.com/t/change-main-display-in-windows-11.964/

**Comment by d0vere** [comment]
no it's not because if i change my main monitor, software and games will open by default on that monitor, and i do not want that behavior.
In windows 10 you could drag the taskbar to a secondary screen without changing the primary monitor.
you can do it in win11 too thanks to other software like explorerpatcher, but i would love a windhawk mod if possible.

**Comment by redactedscribe** [comment]
I recently downloaded Windhawk (thank you @m417z) hoping that I could get rid of both 7+ Taskbar Tweaker and ExplorerPatcher on my Windows 11 system. For my purposes, the former can mostly be replaced by Windhawk, but sadly Windhawk provides no way to move the Win 11 taskbar to a secondary display, which is why ExplorerPatcher must remain installed (I'm guessing this is a hard problem to solve). I've found the latter to often times cause problems when Windows updates, not to mention the infrequent explorer crashes, so it'd be great to no longer have it installed.

In an ideal world, I'd only use Windhawk and be able to set Win 11's native taskbar to only display on my non-primary display. That's the dream, but I guess I'll have to live with ExplorerPatcher some more...

**Comment by RajStartsHere** [comment]
> Done in [Primary taskbar on secondary monitor](https://windhawk.net/mods/taskbar-primary-on-secondary-monitor).

Can We Get Primary Taskbar Controls In Multiple Display?

**Comment by m417z** [comment]
@RajStartsHere I haven't looked at it, but since the taskbar is built with the assumption that there's only one tray area, it's quite possible that it'd be challenging to make it work, things like keeping all tray areas receive the relevant notifications and keeping them all synchronized. I may try implementing it at some point if there's enough demand, but it's unlikely to become available in the near future. Feel free to create a new issue for this suggestion.
