### ISSUE TITLE
Large taskbar icons - Width of taskbar icons

### ISSUE THREAD

**Issue by dr-consit** [ramensoftware/windhawk-mods#45]
When setting the size of the taskbar icons, it seems the width is constant.

I tried poking about and naively adding some width hooks, but this failed, probably because these functions aren't present in the relevant dll.

Anyway if you could point me towards a tool allowing me to list the hookable functions in the relevant dlls, I will have another poke about.

Otherwise, I would greatly appreciate a fix for this issue.

**Comment by dr-consit** [comment]
Nvm about the tool request, I got the list by dumping in a loop in windhawk. Didn't really get me any nearer a solution though.
A cleverer man than I must take over.

**Comment by dr-consit** [comment]
I was wondering if it might be feasible to "change" the DPI of the taskbar? 
I tried intercepting the different DPI calls that I thought might be relevant, but was unable to get anywhere. 
Any pointers would be much appreciated.

**Comment by m417z** [comment]
The [Taskbar Labels for Windows 11](https://windhawk.net/mods/taskbar-labels) mod demonstrates how it's possible to change the width of the taskbar items. It's not very easy, and there's at least one unsolved issue with it: When there are too many items on the taskbar, Windows displays the ["taskbar overflow"](https://winaero.com/how-to-enable-the-new-taskbar-overflow-in-windows-11/). Increasing the items of taskbar buttons cause them to to be inaccessible before the taskbar overflow appears. So, for example, your taskbar might show only 20 items at a time, and if you open 21, the taskbar overflow appears, but if you make the items wider, only 15 can now fit. But still, the taskbar overflow appears only after 20 items.

**Comment by dr-consit** [comment]
@m417z That's very cool, thank you.

Do you have any thoughts about the DPI approach? Any pointers to where to start looking, if I want to try that route, as I imagine it might not cause the mentioned issue?

**Comment by m417z** [comment]
I'm not sure, it depends on the way explorer handles DPI. One thing you can try is hooking functions such as `GetDpiForSystem`, `GetDpiForMonitor`, `GetDpiForWindow`. Another thing you can try is hooking `MulDiv` and replacing the numerator when both the numerator and the denominator are 96 (or a numerator that matches your DPI).

**Comment by imagicalFantasy** [comment]
I hope you will find a way to archive it properly one day !

**Comment by m417z** [comment]
There's no proper solution yet, but you can try installing the [Taskbar Labels for Windows 11](https://windhawk.net/mods/taskbar-labels) mod and setting the desired width, as long as it's small enough to not display labels. It mostly works, but it might have some weird behavior with a large amount of taskbar items, and it doesn't affect pinned items. Feel free to try it and let me know how it goes.

![image](https://user-images.githubusercontent.com/4129781/226111370-8a891a7d-cf81-4272-a618-685945a50dba.png)

**Comment by imagicalFantasy** [comment]
Hi, I tried some week ago the "Taskbar Labels" plugin way. It almost worked but : 

- It don't apply to pinned not open programs
- It don't apply to start menu button
- For icons of opened program, I got a little bit of text overlapping large icon on right.

I know that any tweaking of item width should break the "too many programs" build-in feature.

**Comment by dr-consit** [comment]
I've made a PR: #145 
It works as intended on my machine, any feedback will be most welcome.

**Comment by m417z** [comment]
@imagicalFantasy I did some improvements in Taskbar Labels for Windows 11 version 1.1.2.

> * It don't apply to pinned not open programs

The size is now applied to pinned items if it's smaller than the default Windows 11 size of pinned items.

> * It don't apply to start menu button

That's still the case. Perhaps it's best to create a separate mod for it.

> * For icons of opened program, I got a little bit of text overlapping large icon on right.

What do you mean? Can you show a screenshot and explain how to reproduce it?

**Comment by Gravarty** [comment]
Hm, yeah it only resizes the pinned items only if the labels are way too small. It would be great to have it like on Windows 10 and earlier where the pinned items act like Quick Launch icons with 28px spacing and normal labels, but i guess this isn't possible atm.

![Screenshot_3](https://user-images.githubusercontent.com/16298668/229294475-71ac34a6-199b-4cc3-b17f-400eb5aa5a0d.png)

**Comment by imagicalFantasy** [comment]
@m417z 
It was about use taskbar label mod with goal to change taskbar button width in completion of icon size mod.

But with icon size mod change made by @dr-consit we got the option to change taskbar button width without using the tasbkar label mod. So nothing else is required.

I highly recommend to update icon size mod with change made by @dr-consit.

The only one "con" with custom buttons width is the fact that taskbar overflow (with too many icons) won't understand that we change taskbar button width. But it's hard to full a taskbar of icons.

**Comment by m417z** [comment]
@Gravarty right, currently the mod has code to fetch labels for running programs. To support labels for pinned items, new functionality is needed.

@imagicalFantasy I understand, but as I wrote in the pull request (https://github.com/ramensoftware/windhawk-mods/pull/145#issuecomment-1492961117), I'm reluctant to add it as part of the icon size mod, both because of the code duplication from the taskbar labels mod, and because of the potential incompatibility it introduces.

Of course, you can keep using the fork that @dr-consit created if you prefer.

**Comment by imagicalFantasy** [comment]
@m417z I understand, if we talk only about code, it's could be an aberration. However, for the end user, we have a script that allow change icon size, taskbar height but not button width that could require some tweak to got the best look. Changing icon size is a little bit limited without this. Of course that's still allow to reduce or increase size of icons in the button but it have limits.

For a tweaker, or a programmer, it could make sense that label mod could have impact on button width, but it's a litle bit tricky because it's not the real purpose of this mod. Including the fact that "out of the box" I got some issues to deturn label mods to alter buttons width (like pinned not open, start menu or indesirable parts of label that I personaly don't want) (as I say in my last post) It's why I think label mod is not made for that.

In my case, that's don't have so mush importance, I've a solution that work nicely for me with the fork of @dr-consit. Maybe this version of the mod could be renamed and also put on the store.

Also, maybe you could make a specialized taskbar tweacker mod that allow to change any size of the taskbar elements if you think that icon size mod should not be changed for that.

Anyway,
I'm still happy with Windows modding and Windhawk that really improve Windows experience.

Thank you all for your nice tools !

**Comment by m417z** [comment]
@imagicalFantasy that's a great feedback, thanks. I agree that it's not ideal from a user's point of view.

> I got some issues to deturn label mods to alter buttons width (like pinned not open, start menu or indesirable parts of label that I personaly don't want) (as I say in my last post)

I understand that you found a solution that works for you, but regardless, I'd like to solve these issues, so if you can provide steps to reproduce them and/or attach screenshots, that will help.

> Also, maybe you could make a specialized taskbar tweacker mod that allow to change any size of the taskbar elements if you think that icon size mod should not be changed for that.

I think that it can be a good solution for now which will improve both user experience and programmer experience. @dr-consit what do you think about this suggestion? You can extract your added parts to a separate mod that works alongside the existing mod and submit it. Refer to the readme in the repo for submitting a new mod.

**Comment by m417z** [comment]
I added an option to control the width of taskbar buttons in version 1.2 of the mod.
