### ISSUE TITLE
Classic Explorer navigation bar: Unable to load folder icon when startup

### ISSUE THREAD

**Issue by Lambholl** [ramensoftware/windhawk-mods#612]
![image](https://github.com/ramensoftware/windhawk-mods/assets/55140169/24d5c42c-3655-4b64-b5fd-3129e21c7612)
When a new window of explorer starts, the icon of the folder in the tab doen't show. (Notice the upper left cornor of the picture)
And if I open another folder, it recovered as soon.
![image](https://github.com/ramensoftware/windhawk-mods/assets/55140169/bd0d607f-f683-48b2-bd7d-d5b654530fd8)

Besides, the first time open a window afrer starting explorer, it could't load correctly.
![image](https://github.com/ramensoftware/windhawk-mods/assets/55140169/162753d2-6c6b-4988-92e2-2b4fb47e6bd9)

What's more, the original version of the explorer does not have a separation line between the tab and containers. I hope it could be changed to what it liked before.
![image](https://github.com/ramensoftware/windhawk-mods/assets/55140169/55b650ec-d436-40b6-b61a-b25606dc025d)
![image](https://github.com/ramensoftware/windhawk-mods/assets/55140169/d29f7525-d1f8-4873-9ff3-f7a9ae55b6f2)

**Comment by HtheB** [comment]
This happens for me too after updating with KB5036980 for Windows 11.

**Comment by m417z** [comment]
The issue in the title seems to be fixed now in version 1.0.2 of the mod. The issue with explorer starting with a missing navigation bar is tracked here: https://github.com/ramensoftware/windhawk-mods/issues/487. Regarding the separation line, that's not about the navigation bar so that would be a suggestion for a new mod, feel free to create a new issue for it.
