### ISSUE TITLE
[Vertical Taskbar for Windows 11] Start menu appears behind the taskbar

### ISSUE THREAD

**Issue by gilnett** [ramensoftware/windhawk-mods#730]
[@m417z]
when I click on the window logo the "menu" appears below the taskbar (on its left part)
also the text "search" becomes blurry when it moves
https://github.com/ramensoftware/windhawk-mods/assets/142233342/e520f68c-0da6-4f98-9ff8-6376f6132980

**Comment by m417z** [comment]
> also the text "search" becomes blurry when it moves

Fixed in version 1.1.

> also the text "search" becomes blurry when it moves

You're talking about this search, right?
I'm not sure why or how to fix it, but it's best to replace it with a search icon or hide it completely. It can be done in the Windows taskbar properties.

![image](https://github.com/user-attachments/assets/84452711-b411-4cba-b328-24ab63c72aab)
