### ISSUE TITLE
[Vertical Taskbar for Windows 11] Please make the panels pop out from click location. 

### ISSUE THREAD

**Issue by bagarwa** [ramensoftware/windhawk-mods#756]
Author @m417z 

Love the mod. And I have some feedback / feature request for it. 

With this mod, though the taskbar moves to the left side, certain taskbar related actions remain in their original place.

- Clicking Start button / Search button opens those panels at bottom center of screen, instead of left center.
- Clicking OneDrive icon in system tray now opens a floating OneDrive window at bottom center of screen.
- Clicking [WiFi-Volume-Battery] part of the taskbar opens that panel at bottom right corner, instead of bottom left.
- Clicking [date-time-notification] part of the taskbar opens that panel at bottom right corner, instead of bottom left.

The disconnect between the click point [action], and result is a little jarring. Typically, users expect results to happen at the same place where the action was taken.

So my feature request is - if possible - please make the relevant panels pop out from where the click happens. 
i.e. when I move the task bar to left side and click the start button at left center, the start menu should pop-out from that left center, not the stock bottom center. 

And so on.

**Comment by m417z** [comment]
Hi, thanks for the feedback.

> * Clicking Start button / Search button opens those panels at bottom center of screen, instead of left center.
> * Clicking [WiFi-Volume-Battery] part of the taskbar opens that panel at bottom right corner, instead of bottom left.
> * Clicking [date-time-notification] part of the taskbar opens that panel at bottom right corner, instead of bottom left.

Fixed in version 1.1.

> * Clicking OneDrive icon in system tray now opens a floating OneDrive window at bottom center of screen.

That's more tricky to fix since that's where OneDrive decides to open its floating window. There are two possible ways to approach it:

* Change the vertical taskbar implementation to make OneDrive open the popup in the right place. Due to the way the mod is implemented, that'd be a lot of work, not something I'm willing to do only for OneDrive.
* Change OneDrive to use a more correct way to decide where to open the pop-up. I could write a mod for OneDrive but it feels like an overkill at this point.

I'll keep an eye on this problem, and will wait for feedback from other users, and about other programs that perhaps have this problem as well, before I decide how to approach this.
