### ISSUE TITLE
Remove-Command-Bar mod crashes on 32-bit apps

### ISSUE THREAD

**Issue by Undisputed00x** [ramensoftware/windhawk-mods#865]
As the title says the mod crashes when trying to open explorer dialogs through all 32-bit executables. 32-bit apps that i have used and the app crashed due to the mod's fault were for example **Resource Hacker, Windows Style Builder, Windows MCT etc.**

<details><summary>Resource Hacker example vid</summary>
<p>

https://github.com/user-attachments/assets/355283f9-de22-473d-afb2-729a6056b1c8

</p>
</details>

<details><summary>Windows MCT example vid</summary>
<p>

https://github.com/user-attachments/assets/02715e7f-2a3d-4b30-9013-b501b9da1f18

</p>
</details>

**Comment by CyprinusCarpio** [comment]
Thanks for the report.
You seem to have added those executables in the custom process inclusion list. Remove Command Bar is meant to be used with explorer.exe only, to enable various pre-Vista mods. The modern file open/save dialog is not relevant to this mod, as it didn't exist pre-Vista.
In hindsight I should have limited this mod to 64bit too, because like all my mods it only hooks explorer.exe (by default), and if your explorer.exe is 32bit then you've got worse problems to worry about than how it looks.

That being said, I'll see if I can diagnose this and do a fix, if not I'll limit it to 64bit executables too.

**Comment by CyprinusCarpio** [comment]
I decided to limit this mod to 64bit only. The way this mod is made I can't guarantee it's proper function in any application besides explorer, so use it at your own risk.
