### ISSUE TITLE
[Slick Window Arrangement] Other windows all minimize when dragging a window near the taskbar

### ISSUE THREAD

**Issue by AstudilloMarillo** [ramensoftware/windhawk-mods#897]
@m417z 

Not sure what causes this. When I move a window near the taskbar so it snaps to it, and then move it away again, _sometimes_, all other windows minimize. It's weird, and I can't fully tell you exactly what the steps are to reproduce it. I do know it only happens when the Slick Window Arrangement mod is active. It's pretty annoying, so I hope it can be fixed.

**Comment by m417z** [comment]
Maybe it's caused by this option:
https://www.majorgeeks.com/content/page/enable_disable_aero_shake.html

Regardless of the mod, I hate it and always disable it. Perhaps the mod causes it to be more likely to be triggered, because the windows get some extra movement.

Let me know if disabling it helps.

**Comment by AstudilloMarillo** [comment]
It seems you were right! The 'Title bar window shake' was the problem. Although I didn't have an option to change it in the settings, using the Registry tweak from this website turned the option off and fixed this issue:
https://answers.microsoft.com/en-us/windows/forum/all/the-setting-to-disable-title-bar-window-shake/57ab158b-c7a8-40d1-9a71-7699aea41c89
